Traceback (most recent call last):
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 782, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 172, in ensure_async
    result = await obj
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/nrosi/conda/envs/jupybook/lib/python3.10/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 100 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['%%time', '# Function which defines RHS of ODE system using the FFT.', 'def RHS_KS( u , t, kappa ):', '    ', '    """']
...
['u0 = np.cos( x / 16 ) * ( 1 + np.sin( x / 16 ) )', '', '# Simulate in Fourier frequency domain.', 'u = odeint( RHS_KS , u0 , t , args = ( kappa , ) ) ', 'u = u.T']
-------------------

